-- Bolt referral tables.
--
-- Built from Bolt Tables v2.xlsx, Sheet1. That sheet is the specification; this file
-- implements it. Six tables: the five drawn on the sheet plus verification_matrix, which is
-- rows 15 to 30 of the sheet stored as data so the rule is readable by link.
--
-- Lives alone in a dedicated Supabase project. Tables go in public because nothing else
-- shares the database.
--
-- Safe to re-run: drops its own objects first.

drop table if exists public.grant_patient_discount cascade;
drop table if exists public.grant_friend_discount cascade;
drop table if exists public.verification_matrix cascade;
drop table if exists public.friends cascade;
drop table if exists public.claims cascade;
drop table if exists public.patients cascade;
drop function if exists public.sync_successful_referrals() cascade;
drop function if exists public.is_first_claim(uuid);
drop function if exists public.decide_friend(uuid, boolean);
drop function if exists public.decide_patient(uuid);

-- ---------------------------------------------------------------- patients
-- The account list. Source: customer records. A row is an account, not a person.
-- successful_referrals is not a column: it is counted live by the function at the bottom of
-- this file, so it can never drift from the payout log.

create table public.patients (
  patient_id           uuid primary key default gen_random_uuid(),
  referrer_id          uuid references public.patients(patient_id),  -- who referred them. Null only for the root account
  -- Maintained by the trigger at the bottom of this file, never written by hand: it is
  -- recomputed from released payouts every time one changes, so it cannot drift.
  successful_referrals int not null default 0,
  first_name           text not null,
  last_name            text not null,
  email                text unique not null,
  phone                text unique not null,
  address_line         text,
  postcode             text,
  payment_fingerprint  text,
  customer_since       timestamptz not null default now()
);

-- ------------------------------------------------------------------ claims
-- One row per discount link click. Source: events. Exists before any account does, which is
-- the point: a closed tab no longer ends the referral.

create table public.claims (
  claim_id          uuid primary key default gen_random_uuid(),
  referrer_id       uuid not null references public.patients(patient_id),
  claim_channel     text,
  friend_email      text,
  friend_phone      text,
  creation_date     timestamptz not null default now(),
  expiry_date       timestamptz not null default now() + interval '6 months',
  claim_status      text not null default 'discount_code_clicked'
                      check (claim_status in ('discount_code_clicked','account_created',
                                              'transaction_paid','transaction_delivered',
                                              'transaction_success')),
  friend_patient_id uuid references public.patients(patient_id),  -- filled when the order completes
  check (friend_email is not null or friend_phone is not null)
);

-- ----------------------------------------------------------------- friends
-- The onboarded friend's own details, as typed at registration. Source: verification
-- records. What the checks compare against the patient list.

create table public.friends (
  claim_id     uuid primary key references public.claims(claim_id),
  first_name   text not null,
  last_name    text not null,
  email        text not null,
  phone        text not null,
  address_line text,
  postcode     text
);

-- ------------------------------------------------------- verification_matrix
-- Rows 15 to 30 of the sheet. Y means that field matches an existing patient, contacts
-- distinct. The whole rule in sixteen readable rows: manual when both names match, else yes.
-- The note is the sentence a reviewer is shown.

create table public.verification_matrix (
  first_name_match boolean not null,
  last_name_match  boolean not null,
  address_match    boolean not null,
  postcode_match   boolean not null,
  approved         text not null check (approved in ('yes','manual')),
  note             text,
  primary key (first_name_match, last_name_match, address_match, postcode_match)
);

-- ---------------------------------------------------- grant_friend_discount
-- Job: check the claimant is not an existing patient, then grant their discount. UK photo
-- IDs carry no number to dedupe on, so a name conflict goes to a human with the ID.
-- One row per claim, written by decide_friend and nothing else.

create table public.grant_friend_discount (
  claim_id                    uuid primary key references public.claims(claim_id),
  first_name_match            boolean,
  last_name_match             boolean,
  address_match               boolean,
  postcode_match              boolean,
  -- Generated by the database from the two name columns: the rule as a column definition.
  manual_verification_needed  boolean generated always as
                                (first_name_match and last_name_match) stored,
  manual_approved             boolean,   -- null is the sheet's NA: no human has looked yet
  approved                    boolean,   -- null: not decidable yet
  verdict_note                text,      -- copied from the matrix at decision time, never regenerated
  within_window               boolean,
  release_friend_discount     boolean not null default false,
  transaction_status          text check (transaction_status in ('paid','delivered','success')),
  -- Copied from the claim so the index below can refuse a second release per friend.
  friend_patient_id           uuid references public.patients(patient_id),
  check (not release_friend_discount or (approved is true and within_window is true))
);

-- One released discount per human, ever. The second attempt errors instead of double-paying.
create unique index one_release_per_friend
  on public.grant_friend_discount (friend_patient_id)
  where release_friend_discount;

-- --------------------------------------------------- grant_patient_discount
-- Job: check the referrer can get their bonus. 80 for their first successful claim, 40
-- after. One row per claim, written by decide_patient and nothing else.

create table public.grant_patient_discount (
  claim_id                 uuid primary key references public.claims(claim_id),
  -- Copied from the claim so the index below can refuse a second 80 per referrer.
  referrer_id              uuid not null references public.patients(patient_id),
  transaction_status       text check (transaction_status in ('paid','delivered','success')),
  transaction_success      boolean not null default false,
  first_claim              boolean,
  referral_amount          int check (referral_amount in (80, 40)),
  release_patient_discount boolean not null default false,
  check (not release_patient_discount or (transaction_success and referral_amount is not null))
);

-- One 80 per referrer, ever. Two first claims racing both read zero prior payouts; this
-- makes the second insert fail instead of overpaying.
create unique index one_first_claim_per_referrer
  on public.grant_patient_discount (referrer_id)
  where referral_amount = 80;

-- ----------------------------------------------------------------- functions

-- The counter that cannot drift: a real column on patients, recomputed from released
-- payouts by this trigger every time one changes. Visible in the Table Editor, and no code
-- path increments it by hand.
create or replace function public.sync_successful_referrals()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_ins uuid; v_del uuid;   -- NEW exists only on insert/update, OLD only on update/delete
begin
  if tg_op in ('INSERT','UPDATE') then v_ins := new.referrer_id; end if;
  if tg_op in ('UPDATE','DELETE') then v_del := old.referrer_id; end if;
  update public.patients p
     set successful_referrals =
       (select count(*) from public.grant_patient_discount g
         where g.referrer_id = p.patient_id and g.release_patient_discount)
   where p.patient_id = any (array[v_ins, v_del]);
  return null;
end $$;

create trigger trg_sync_successful_referrals
after insert or update or delete on public.grant_patient_discount
for each row execute function public.sync_successful_referrals();

create or replace function public.is_first_claim(p_referrer_id uuid)
returns boolean language sql stable as $$
  select not exists (select 1 from public.grant_patient_discount g
                      where g.referrer_id = p_referrer_id and g.release_patient_discount);
$$;

-- The friend side. Gathers the four match booleans, looks them up in the matrix, writes one
-- row. The manual verdict comes in as an argument because a human makes it, not this
-- function. Deletes and rewrites its own row, so running it twice changes nothing.
create or replace function public.decide_friend(p_claim_id uuid,
                                                p_manual_approved boolean default null)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_claim    public.claims;
  v_friend   public.friends;
  v_resolved public.patients;
  v_fn boolean; v_ln boolean; v_ad boolean; v_pc boolean;
  v_rule     public.verification_matrix;
  v_approved boolean; v_note text; v_window boolean; v_release boolean;
begin
  delete from public.grant_friend_discount where claim_id = p_claim_id;
  select * into v_claim from public.claims where claim_id = p_claim_id;
  select * into v_friend from public.friends where claim_id = p_claim_id;
  v_window := now() < v_claim.expiry_date;

  if v_claim.friend_patient_id is not null then
    select * into v_resolved from public.patients
     where patient_id = v_claim.friend_patient_id;
  end if;

  -- Already a customer: the claim resolved to an account that predates it. Nothing to
  -- verify, nothing to grant, and the matrix never runs.
  if v_resolved.patient_id is not null
     and v_resolved.customer_since < v_claim.creation_date then
    insert into public.grant_friend_discount
      (claim_id, approved, verdict_note, within_window,
       release_friend_discount, friend_patient_id)
    values
      (p_claim_id, false,
       'the claimed contact already belongs to an account opened before the claim',
       v_window, false, v_claim.friend_patient_id);
    return;
  end if;

  -- No registration and no resolved account: nothing to compare, nothing decided,
  -- nothing refused.
  if v_friend.claim_id is null and v_resolved.patient_id is null then
    insert into public.grant_friend_discount
      (claim_id, approved, verdict_note, within_window, release_friend_discount)
    values
      (p_claim_id, null, 'no account yet, so there is nothing to check', v_window, false);
    return;
  end if;

  -- What to compare: the registration details, or the resolved account when the friend
  -- registered through a different claim (two claims, one person).
  if v_friend.claim_id is null then
    v_friend.first_name   := v_resolved.first_name;
    v_friend.last_name    := v_resolved.last_name;
    v_friend.address_line := v_resolved.address_line;
    v_friend.postcode     := v_resolved.postcode;
  end if;

  -- The four comparisons, against every patient except the friend's own account.
  select
    bool_or(p.first_name = v_friend.first_name),
    bool_or(p.last_name = v_friend.last_name),
    bool_or(p.address_line is not null and p.address_line = v_friend.address_line),
    bool_or(p.postcode is not null and p.postcode = v_friend.postcode)
  into v_fn, v_ln, v_ad, v_pc
  from public.patients p
  where p.patient_id is distinct from v_claim.friend_patient_id;

  v_fn := coalesce(v_fn, false); v_ln := coalesce(v_ln, false);
  v_ad := coalesce(v_ad, false); v_pc := coalesce(v_pc, false);

  select * into v_rule from public.verification_matrix
   where first_name_match = v_fn and last_name_match = v_ln
     and address_match = v_ad and postcode_match = v_pc;

  -- The matrix decides, except where it says a human does.
  if v_rule.approved = 'manual' then
    v_approved := p_manual_approved;   -- null until the photo ID check happens
    v_note := coalesce(v_rule.note, 'both names match an existing patient')
              || case when p_manual_approved is null
                        then '. awaiting manual photo ID check'
                      when p_manual_approved
                        then '. photo ID checked: a distinct person'
                      else '. photo ID checked: an existing patient' end;
  else
    v_approved := true;
    v_note := coalesce(v_rule.note,
                       'nothing here identifies this person as an existing patient');
  end if;

  -- Released once per human. If another claim already released for this person, this one
  -- never does, and the index at the top of the file enforces it even if this code lied.
  v_release := coalesce(v_approved, false) and v_window;
  if v_release and v_claim.friend_patient_id is not null
     and exists (select 1 from public.grant_friend_discount g
                  where g.friend_patient_id = v_claim.friend_patient_id
                    and g.release_friend_discount and g.claim_id <> p_claim_id) then
    v_release := false;
    v_note := v_note || '. an earlier claim already released for this person; '
                     || 'the successful claim keeps it';
  end if;

  insert into public.grant_friend_discount
    (claim_id, first_name_match, last_name_match, address_match, postcode_match,
     manual_approved, approved, verdict_note, within_window,
     release_friend_discount, transaction_status, friend_patient_id)
  values
    (p_claim_id, v_fn, v_ln, v_ad, v_pc,
     p_manual_approved, v_approved, v_note, v_window,
     v_release,
     case v_claim.claim_status when 'transaction_paid' then 'paid'
                               when 'transaction_delivered' then 'delivered'
                               when 'transaction_success' then 'success' end,
     v_claim.friend_patient_id);
end $$;

-- The referrer side. first_claim is counted at this moment, the amount follows it, and the
-- release needs the same claim's friend discount to have released first.
create or replace function public.decide_patient(p_claim_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_claim   public.claims;
  v_success boolean;
  v_first   boolean;
  v_amount  int;
  v_friend_released boolean;
  -- is_first_claim stays the API's live answer; the derivation above is this function's,
  -- because it must survive its own delete-and-rewrite.
begin
  delete from public.grant_patient_discount where claim_id = p_claim_id;
  select * into v_claim from public.claims where claim_id = p_claim_id;

  v_success := v_claim.claim_status = 'transaction_success';
  -- First means: no released claim of this referrer was created earlier. Anchored to
  -- creation order, not decision order, so re-running a decision can never flip an 80 to
  -- a 40: the function deletes its own row first, and a count of the remaining rows would.
  v_first := not exists (
    select 1 from public.grant_patient_discount g
    join public.claims c2 on c2.claim_id = g.claim_id
    where g.referrer_id = v_claim.referrer_id and g.release_patient_discount
      and (c2.creation_date, c2.claim_id) < (v_claim.creation_date, v_claim.claim_id));
  select release_friend_discount into v_friend_released
    from public.grant_friend_discount where claim_id = p_claim_id;

  -- The amount exists only once the order completed. An unpriced pending claim keeps the
  -- one-80-per-referrer index honest.
  v_amount := case when v_success then (case when v_first then 80 else 40 end) end;

  insert into public.grant_patient_discount
    (claim_id, referrer_id, transaction_status, transaction_success,
     first_claim, referral_amount, release_patient_discount)
  values
    (p_claim_id, v_claim.referrer_id,
     case v_claim.claim_status when 'transaction_paid' then 'paid'
                               when 'transaction_delivered' then 'delivered'
                               when 'transaction_success' then 'success' end,
     v_success, v_first, v_amount,
     v_success and coalesce(v_friend_released, false) and v_amount is not null);
end $$;

-- ------------------------------------------------------------- public read
-- Every person in these tables is invented and the phone numbers come from Ofcom's test
-- range, so the rows are readable by anyone. Read only: nothing grants insert, update or
-- delete to anyone. The two decide functions are not part of the public surface.

alter table public.patients               enable row level security;
alter table public.claims                 enable row level security;
alter table public.friends                enable row level security;
alter table public.verification_matrix    enable row level security;
alter table public.grant_friend_discount  enable row level security;
alter table public.grant_patient_discount enable row level security;

create policy "public read" on public.patients               for select to anon using (true);
create policy "public read" on public.claims                 for select to anon using (true);
create policy "public read" on public.friends                for select to anon using (true);
create policy "public read" on public.verification_matrix    for select to anon using (true);
create policy "public read" on public.grant_friend_discount  for select to anon using (true);
create policy "public read" on public.grant_patient_discount for select to anon using (true);

grant select on all tables in schema public to anon;
grant execute on function public.is_first_claim(uuid) to anon;
revoke execute on function public.sync_successful_referrals() from public, anon;
revoke execute on function public.decide_friend(uuid, boolean) from public, anon;
revoke execute on function public.decide_patient(uuid) from public, anon;
